"""Tool formatting and response parsing utilities for open-weights and local models.

Provides standardized schemas and prompt templates allowing open-weights models
(HuggingFace Pipeline, vLLM, Ollama, etc.) to participate in agentic tool-use benchmarks.
"""

from __future__ import annotations

import json
import re
import uuid
from typing import Any


def format_tools_system_prompt(tools: list[dict[str, Any]]) -> str:
    """Format a list of tool definitions into a system instruction prompt.

    Args:
        tools: List of tool schemas (OpenAI function/tool format).

    Returns:
        String instructions describing available tools and invocation format.
    """
    tools_formatted = json.dumps(tools, indent=2)
    return (
        "## Available Tools\n"
        "You have access to the following callable tools:\n"
        f"```json\n{tools_formatted}\n```\n\n"
        "## Tool Calling Instructions\n"
        "To invoke a tool, you must output an XML `<tool_call>` block formatted as:\n"
        "<tool_call>\n"
        '{"name": "<tool_name>", "arguments": {<arguments_object>}}\n'
        "</tool_call>\n\n"
        "You may provide reasoning before calling a tool. If no tool call is needed, "
        "respond directly with your final answer."
    )


def inject_tools_into_messages(
    messages: list[dict[str, Any]], tools: list[dict[str, Any]] | None
) -> list[dict[str, Any]]:
    """Inject tool definitions into the conversation messages.

    If tools is None or empty, returns a copy of messages unchanged.
    If messages contains a system message, appends the tool prompt to it.
    Otherwise, inserts a new system message at the beginning of the list.

    Args:
        messages: Conversation turn dictionaries with 'role' and 'content'.
        tools: Optional list of tool schemas.

    Returns:
        New list of messages with tool instructions included.
    """
    if not tools:
        return [dict(m) for m in messages]

    tools_prompt = format_tools_system_prompt(tools)
    new_messages: list[dict[str, Any]] = [dict(m) for m in messages]

    # Find existing system message
    system_idx = next(
        (i for i, m in enumerate(new_messages) if m.get("role") == "system"), None
    )

    if system_idx is not None:
        existing_content = str(new_messages[system_idx].get("content", ""))
        new_messages[system_idx]["content"] = f"{existing_content}\n\n{tools_prompt}"
    else:
        new_messages.insert(0, {"role": "system", "content": tools_prompt})

    return new_messages


def extract_tool_calls_from_text(
    text: str,
) -> tuple[str, list[dict[str, Any]]]:
    """Extract tool calls from generated model text across common open-weights formats.

    Supports:
    1. Standard XML tag format: `<tool_call>{"name": ..., "arguments": ...}</tool_call>`
    2. ReAct format: `Action: <name>\nAction Input: {<json>}`
    3. Markdown JSON block: ```json {"name": ..., "arguments": ...} ```
    4. Top-level raw JSON: `{"name": ..., "arguments": ...}`

    Args:
        text: Raw text generated by model.

    Returns:
        Tuple of (cleaned_content, list_of_tool_calls).
        Each tool call is a dictionary: `{"id": str, "name": str, "arguments": dict}`.
    """
    tool_calls: list[dict[str, Any]] = []
    cleaned_text = text

    # Pattern 1: <tool_call> ... </tool_call>
    xml_pattern = re.compile(r"<tool_call>\s*(\{.*?\})\s*</tool_call>", re.DOTALL)
    for match in xml_pattern.finditer(text):
        raw_json = match.group(1)
        try:
            parsed = json.loads(raw_json)
            name = parsed.get("name") or parsed.get("tool")
            raw_args = parsed.get("arguments", {})
            if isinstance(raw_args, str):
                try:
                    args = json.loads(raw_args)
                except Exception:
                    args = {"_raw": raw_args}
            elif isinstance(raw_args, dict):
                args = raw_args
            else:
                args = {}

            if name:
                tool_calls.append({
                    "id": f"call_{uuid.uuid4().hex[:8]}",
                    "name": str(name),
                    "arguments": args,
                })
        except Exception:
            pass

    if tool_calls:
        cleaned_text = xml_pattern.sub("", cleaned_text).strip()
        return cleaned_text, tool_calls

    # Pattern 2: Action: ... \nAction Input: ... (ReAct format)
    react_pattern = re.compile(
        r"Action:\s*([a-zA-Z0-9_-]+)\s*\nAction Input:\s*(\{.*?\})", re.DOTALL
    )
    for match in react_pattern.finditer(text):
        name = match.group(1)
        raw_args = match.group(2)
        try:
            args = json.loads(raw_args)
            if not isinstance(args, dict):
                args = {"_raw": raw_args}
            tool_calls.append({
                "id": f"call_{uuid.uuid4().hex[:8]}",
                "name": str(name),
                "arguments": args,
            })
        except Exception:
            pass

    if tool_calls:
        cleaned_text = react_pattern.sub("", cleaned_text).strip()
        return cleaned_text, tool_calls

    # Pattern 3: ```json {"name": ..., "arguments": ...} ```
    md_pattern = re.compile(
        r"```(?:json)?\s*(\{\s*\"(?:name|tool)\":.*?\})\s*```", re.DOTALL
    )
    for match in md_pattern.finditer(text):
        raw_json = match.group(1)
        try:
            parsed = json.loads(raw_json)
            name = parsed.get("name") or parsed.get("tool")
            raw_args = parsed.get("arguments", {})
            if isinstance(raw_args, str):
                try:
                    args = json.loads(raw_args)
                except Exception:
                    args = {"_raw": raw_args}
            elif isinstance(raw_args, dict):
                args = raw_args
            else:
                args = {}

            if name:
                tool_calls.append({
                    "id": f"call_{uuid.uuid4().hex[:8]}",
                    "name": str(name),
                    "arguments": args,
                })
        except Exception:
            pass

    if tool_calls:
        cleaned_text = md_pattern.sub("", cleaned_text).strip()
        return cleaned_text, tool_calls

    # Pattern 4: Top-level raw JSON object
    trimmed = text.strip()
    if trimmed.startswith("{") and trimmed.endswith("}"):
        try:
            parsed = json.loads(trimmed)
            name = parsed.get("name") or parsed.get("tool")
            if name:
                raw_args = parsed.get("arguments", {})
                if isinstance(raw_args, str):
                    try:
                        args = json.loads(raw_args)
                    except Exception:
                        args = {"_raw": raw_args}
                elif isinstance(raw_args, dict):
                    args = raw_args
                else:
                    args = {}
                tool_calls.append({
                    "id": f"call_{uuid.uuid4().hex[:8]}",
                    "name": str(name),
                    "arguments": args,
                })
                cleaned_text = ""
        except Exception:
            pass

    return cleaned_text, tool_calls
